#!/usr/bin/env python3
"""In-container BattleSnake verifier for the RevengeBench Harbor task.

This is the *scoring* half of the interactive (Tier I) RevengeBench artifact.
It runs at verification time (Harbor mounts ``/tests`` only then, so it stays
hidden from the agent during its work session) and:

1. Extracts target-observed states from fresh hidden verifier traces and writes
   an unlabeled query artifact.
2. Runs the agent's hypothesized policy from ``/workspace/main.py`` as the
   unprivileged ``agent`` user to produce an action artifact.
3. Replays those actions, offline, against fresh hidden target traces generated by the
   verifier (``sim_*.jsonl`` produced by target-vs-opponent simulation).
4. Writes ``eval.json`` (the native trace summary) plus a scalar ``reward.txt``.

Single source of truth
-----------------------
Scoring is delegated to the shared BattleSnake trace scorer in
``revenge_bench.traces.offline_eval``. Harbor supplies an artifact-backed move
provider so learner-authored code never executes in the root process that can
read hidden verifier traces; stdout/stderr are logs only.

The authoritative metric is ``mean_distance`` (lower is better), matching the
native inverse-strategy ranking. ``reward.txt`` is a Harbor-only presentation
scalar: Harbor treats reward as higher-is-better, so we emit ``1 - mean_distance``
(a monotone transform of the authoritative metric, **not** a separate score).

The image installs ``revenge_bench`` with ``--no-deps`` plus ``zstandard`` (the
only import-time dependency of the BattleSnake parser), keeping the scorer image
lean while reusing the real scoring code.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


def _load_deps():
    """Import the shared scorer, failing loudly."""
    try:
        from revenge_bench.traces.offline_eval import (
            evaluate_battlesnake_submission_with_move_provider,
            find_battlesnake_sim_files,
        )
        from revenge_bench.traces.parsers.battlesnake import extract_state_action_pairs
    except Exception as exc:  # noqa: BLE001 - surface missing install clearly
        print(f"ERROR: could not import scoring dependencies: {exc}", file=sys.stderr)
        raise
    return (
        evaluate_battlesnake_submission_with_move_provider,
        find_battlesnake_sim_files,
        extract_state_action_pairs,
    )


class BattleSnakeArtifactMoveProvider:
    """Return precomputed learner actions from an action artifact."""

    def __init__(self, actions: list[Any]) -> None:
        self.actions = actions
        self.index = 0

    def __call__(self, _state: dict) -> Any:
        if self.index >= len(self.actions):
            return None
        action = self.actions[self.index]
        self.index += 1
        return action


def _collect_queries(labels_dir: Path, target_name: str) -> list[dict[str, Any]]:
    _evaluate, find_battlesnake_sim_files, extract_state_action_pairs = _load_deps()
    queries: list[dict[str, Any]] = []
    for sim_file in find_battlesnake_sim_files(labels_dir):
        try:
            for target_state, _target_action in extract_state_action_pairs(
                sim_file, target_name
            ):
                queries.append({"id": len(queries), "state": target_state})
        except Exception as exc:  # noqa: BLE001 - mirror tolerant scoring
            print(f"WARNING: failed to collect queries from {sim_file}: {exc}", file=sys.stderr)
    return queries


def _write_queries(path: Path, queries: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for query in queries:
            handle.write(json.dumps(query, separators=(",", ":")) + "\n")


def _read_actions(path: Path, expected: int) -> list[Any]:
    actions: list[Any] = [None] * expected
    if not path.exists():
        return actions
    with path.open(encoding="utf-8") as handle:
        for fallback_id, line in enumerate(handle):
            line = line.strip()
            if not line:
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            idx = payload.get("id", fallback_id)
            if isinstance(idx, int) and 0 <= idx < expected:
                actions[idx] = payload.get("action")
    return actions


def _write_runner_status(
    out_dir: Path,
    *,
    status: str,
    returncode: int | None = None,
    timeout_sec: int | None = None,
    message: str | None = None,
) -> None:
    payload = {
        "status": status,
        "returncode": returncode,
        "timeout_sec": timeout_sec,
        "message": message,
    }
    (out_dir / "learner-runner.status.json").write_text(
        json.dumps(payload, indent=2) + "\n"
    )


def _run_action_artifact(
    *,
    submission: Path,
    runner: Path,
    user: str,
    out_dir: Path,
    queries: list[dict[str, Any]],
) -> list[Any]:
    run_root = Path("/run/revengebench_eval")
    artifact_dir = (
        run_root / "battlesnake"
        if Path("/run").is_dir() and os.access("/run", os.W_OK)
        else out_dir / "action_artifacts"
    )
    if artifact_dir.exists():
        for child in artifact_dir.iterdir():
            child.unlink()
    artifact_dir.mkdir(parents=True, exist_ok=True)
    queries_path = artifact_dir / "queries.jsonl"
    actions_path = artifact_dir / "actions.jsonl"
    _write_queries(queries_path, queries)

    if subprocess.run(["id", "-u"], capture_output=True, text=True).stdout.strip() == "0":
        if subprocess.run(["id", user], capture_output=True).returncode != 0:
            raise RuntimeError(f"scorer user {user!r} does not exist")
        try:
            import shutil

            shutil.chown(artifact_dir, user=user, group=user)
            shutil.chown(queries_path, user=user, group=user)
        except Exception:
            os.chmod(artifact_dir, 0o777)
        cmd = ["runuser", "-u", user, "--"]
    else:
        cmd = []

    stdout_path = out_dir / "learner-runner.stdout"
    stderr_path = out_dir / "learner-runner.stderr"
    base_cmd = [
        "env",
        "-i",
        "HOME=/home/agent",
        "PATH=/usr/local/bin:/usr/bin:/bin",
        "PYTHONNOUSERSITE=1",
        "python3",
        "-I",
        str(runner),
        "--submission",
        str(submission),
        "--queries",
        str(queries_path),
        "--actions",
        str(actions_path),
    ]
    with stdout_path.open("w", encoding="utf-8") as stdout, stderr_path.open(
        "w", encoding="utf-8"
    ) as stderr:
        try:
            proc = subprocess.run(
                [*cmd, *base_cmd],
                stdout=stdout,
                stderr=stderr,
                text=True,
                timeout=300,
            )
        except subprocess.TimeoutExpired as exc:
            stderr.write(f"\nBattleSnake learner runner timed out after {exc.timeout}s\n")
            _write_runner_status(
                out_dir,
                status="timeout",
                timeout_sec=int(exc.timeout or 300),
                message="scoring degraded to missing actions",
            )
            return _read_actions(actions_path, len(queries))
    if proc.returncode != 0:
        _write_runner_status(
            out_dir,
            status="nonzero_exit",
            returncode=proc.returncode,
            message="scoring degraded to runner-provided or missing actions",
        )
    else:
        _write_runner_status(out_dir, status="ok", returncode=0)
    return _read_actions(actions_path, len(queries))


def score(
    submission: Path,
    labels_dir: Path,
    target_name: str,
    round_num: int,
    runner: Path,
    runner_user: str,
    out_dir: Path,
    learner_name: str = "learner",
) -> dict:
    """Score ``submission`` against the frozen target traces in ``labels_dir``.

    Returns the native trace summary dict (also written to ``eval.json``) — the
    same object the tournament writes to ``traces.json``. On no frozen traces or
    an unscorable policy, returns ``{"error": ...}``.
    """
    (
        evaluate_battlesnake_submission_with_move_provider,
        find_battlesnake_sim_files,
        _extract_state_action_pairs,
    ) = _load_deps()

    if not find_battlesnake_sim_files(labels_dir):
        return {"error": f"No frozen sim_*.jsonl traces found in {labels_dir}"}

    queries = _collect_queries(labels_dir, target_name)
    actions = _run_action_artifact(
        submission=submission,
        runner=runner,
        user=runner_user,
        out_dir=out_dir,
        queries=queries,
    )
    provider = BattleSnakeArtifactMoveProvider(actions)
    return evaluate_battlesnake_submission_with_move_provider(
        round_dir=labels_dir,
        round_num=round_num,
        target_name=target_name,
        learner_name=learner_name,
        move_provider=provider,
        evaluation_type="offline_artifact",
        include_diagnostics=True,
    )


def _reward_from_summary(payload: dict) -> float:
    """Map the authoritative ``mean_distance`` to Harbor's higher-is-better reward.

    Harbor reads ``reward.txt`` as a scalar where larger is better, so we emit
    ``1 - mean_distance`` — a monotone transform of the native metric, not a new
    score. An unscorable submission (error / non-finite distance) maps to ``0.0``
    (the same value Harbor falls back to when no reward is written).
    """
    if payload.get("error"):
        return 0.0
    md = payload.get("mean_distance")
    if not isinstance(md, (int, float)) or not math.isfinite(md):
        return 0.0
    return 1.0 - float(md)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--submission", default="/workspace/main.py")
    parser.add_argument(
        "--labels",
        default="/run/verifier_labels/rounds/1",
        help="Directory of fresh hidden target sim_*.jsonl traces.",
    )
    parser.add_argument("--target-name", default="target")
    parser.add_argument("--learner-name", default="learner")
    parser.add_argument("--round", type=int, default=1)
    parser.add_argument("--runner", default="/tests/battlesnake_learner_runner.py")
    parser.add_argument("--runner-user", default="agent")
    parser.add_argument(
        "--out-dir",
        default="/logs/verifier",
        help="Where to write eval.json and reward.txt.",
    )
    args = parser.parse_args(argv)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    payload = score(
        submission=Path(args.submission),
        labels_dir=Path(args.labels),
        target_name=args.target_name,
        round_num=args.round,
        runner=Path(args.runner),
        runner_user=args.runner_user,
        out_dir=out_dir,
        learner_name=args.learner_name,
    )

    reward = _reward_from_summary(payload)
    (out_dir / "eval.json").write_text(json.dumps(payload, indent=2))
    (out_dir / "reward.txt").write_text(f"{reward}\n")

    md = payload.get("mean_distance")
    md_str = (
        f"{md:.4f}" if isinstance(md, (int, float)) and math.isfinite(md) else "n/a"
    )
    print(
        f"BattleSnake eval: mean_distance={md_str} "
        f"reward={reward:.4f} "
        f"({payload.get('total_actions', 0)} actions"
        f", {payload.get('num_simulations', 0)} sims)"
    )
    if payload.get("error"):
        print(f"  note: {payload['error']}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
